services:
  stockfinder:
    container_name: stockfinder
    image: ghcr.io/mikemilligram/stockfinder:latest
    environment:
      COUNTRIES: USA,Germany
      EODHD_API_KEY: ${EODHD_API_KEY}
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - stockfinder

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - stockfinder

volumes:
  mongo_data:

networks:
  stockfinder:
    name: stockfinder_net