services:
  stockfinder:
    build: .
    environment:
      LOG_LEVEL: INFO
      COUNTRIES: USA,Germany
      EODHD_API_KEY: ${EODHD_API_KEY}
      MONGODB_HOST: ${MONGODB_HOST}
    restart: unless-stopped 